name: Minimal Example (main)
on: workflow_dispatch
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build
        uses: hashicorp/actions-go-build@dd7ca5a30c402c933e1fe61e0ff7165e5c4ee9e4 # v1.1.2
        with:
          go_version: 1.24
          os: linux
          arch: amd64
          work_dir: testdata/example-app
          debug: true
          instructions: |
            go build -o "$BIN_PATH" -trimpath -buildvcs=false
